matrix:
  include: 
    - language: android
      android:
        components:
          - tools
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
      before_install:
	- yes | sdkmanager "platforms;android-27"
        - yes | sdkmanager "platforms;android-28"
      before_script:
        - cd Application
      script:
        - ./gradlew build connectedCheck

    - language: node_js
      node_js:
        - "7"
      before_script:
        - cd "RESTful API Server"
        - npm install
      

notifications:
  email:
    - matteo@matteofilia.com
