matrix:
  include: 
    - language: android
      android:
        components:
          - tools
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - extra
      before_script:
        - cd Application
      script:
        - ./gradlew build connectedCheck

    - language: node_js
      node_js:
        - "7"
      before_script:
        - cd "RESTful API Server"
        - npm install
      

notifications:
  email:
    - matteo@matteofilia.com
